# Generated by Django 2.1.3 on 2019-01-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='emp_id',
            new_name='empid',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
